name: sensorize
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  app_links: ^6.3.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  get_it: ^8.0.3
  http: ^1.2.2
  injectable: ^2.4.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  restart_app: ^1.3.2
  smooth_page_indicator: ^1.2.0+3
  wave: ^0.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.2
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - lib/config/env/config.env
    - assets/
    - assets/resources/
    - assets/resources/silo/
    - assets/icon/
